server:
  port: 9999
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/car_retenal_sys?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root
  jpa:
    database: mysql
#    hibernate:
#      ddl-auto: update
    show-sql: true